local Comment(lines) = 
  [
    "# %(line)s" % { line: line }
    for line in (if std.isArray(lines) then lines else [ lines ])
  ];

{
  Config(data):
    std.lines(Comment([
      "*** Do not edit ***",
      "This file is auto-generated by Jsonnet",
    ])) +
    std.manifestYamlDoc(data, indent_array_in_object=false, quote_keys=false),
}
