---
version: '3'
includes:
  jsonnet:
    taskfile: ../../tasks/jsonnet.yml
    internal: true
  clean:
    taskfile: ../../tasks/clean.yml
    internal: true
tasks:
  build:
    cmds:
    - task: jsonnet:build
      vars:
        JSONNET_SOURCE: "bat.jsonnet"
        JSONNET_INCLUDE_DIRS: "-J ../.. -J ."
  clean:config:
    cmds:
    - task: clean:target
      vars:
        TARGETS: config
  clean:
    parallel: true
    cmds:
    - task: clean:config
  default:
    cmds:
    - task: build
