{
  Comment(lines):
    std.lines([
      "# %(line)s" % { line: line }
      for line in (if std.isArray(lines) then lines else [ lines ])
    ]),
  Theme(data, colorful = true):
    $.Comment([
      "*** Do not edit ***",
      "This file is auto-generated by Jsonnet",
    ]) +
    std.manifestYamlDoc(data + {
      colourful: colorful,
    }, indent_array_in_object=false, quote_keys=false),
}
