---
version: '3'
includes:
  launchagents:
    taskfile: ./macos/LaunchAgents/
  gitconfig:
    taskfile: ./conf/git/
  ripgrep-conf:
    taskfile: ./conf/ripgrep/
    internal: true
tasks:
  update:submodules:
    label: " Update submodules"
    desc: "Update all git submodules for this repository."
    cmds:
    - git submodule update --init --recursive --remote --quiet
  generate:
    deps: [ update:submodules ]
    cmds:
    - platforms: [darwin]
      task: launchagents:generate
  install:dry-run:
    label: "󰚩 Install (dry-run)"
    desc: "Install dotfiles using Dotbot using dry-run mode."
    cmds:
    - dotbot -d "$(pwd)" -c "$(pwd)/install.yml" --exit-on-failure --dry-run
    sources:
    - install.yml
  install:macos:defaults:
    label: "Install macos defaults"
    cmds:
    - ./defaults.sh
    dir: "{{.ROOT_DIR}}/macos/"
    sources:
    - defaults.sh
    - "*.defaults.sh"

  reinstall:
    label: "󰚩 Reinstall"
    desc: "Reinstall dotfiles using Dotbot"
    cmds:
    - dotbot -d "$(pwd)" -c "$(pwd)/install.yml" --exit-on-failure --verbose
    - task: launchagents:install
    - task: install:macos:defaults
  install:
    label: "󰚩 Install"
    desc: "Install dotfiles using Dotbot"
    deps: [ generate ] 
    cmds:
    - dotbot -d "$(pwd)" -c "$(pwd)/install.yml" --exit-on-failure
    - task: launchagents:install
    - task: install:macos:defaults
  clean:
    label: "Clean"
    desc: "Clean generated files"
    cmds:
    - task: gitconfig:clean
    - platforms: [darwin]
      task: launchagents:clean
