---
version: '3'
includes:
  launchagents:
    taskfile: ./macos/LaunchAgents/
  gitconfig:
    taskfile: ./conf/git/
  ripgrep-conf:
    taskfile: ./conf/ripgrep/
    internal: true
tasks:
  update:submodules:
    label: " Update submodules"
    desc: "Update all git submodules for this repository."
    cmds:
    - git submodule update --init --recursive --remote --quiet
  generate:
    deps: [ update:submodules ]
    cmds:
    - platforms: [darwin]
      task: launchagents:generate
  install:dry-run:
    label: "󰚩 Install (dry-run)"
    desc: "Install dotfiles using Dotbot using dry-run mode."
    cmds:
    - dotbot -d "$(pwd)" -c "$(pwd)/install.yml" --exit-on-failure --dry-run
    sources:
    - install.yml
  install:macos:defaults:
    label: "Install macos defaults"
    cmds:
    - ./defaults.sh
    dir: "{{.ROOT_DIR}}/macos/"
    sources:
    - defaults.sh
    - "*.defaults.sh"

  dotbot:install:
    # TODO(@s0cks): uncomment this
    # internal: true
    vars:
      PLUGINS_DIR: ".dotbot/plugins"
    cmds: 
    - |
      dotbot \
        --verbose \
        -p {{.PLUGINS_DIR}}/dotbot-mise \
        -p {{.PLUGINS_DIR}}/dotbot-brew \
        -p {{.PLUGINS_DIR}}/dotbot-git \
        -p {{.PLUGINS_DIR}}/dotbot-if \
        -p {{.PLUGINS_DIR}}/dotbot-ifplatform \
        -p {{.PLUGINS_DIR}}/dotbot-ya \
        -p {{.PLUGINS_DIR}}/dotbot-jsonnet \
        -p {{.PLUGINS_DIR}}/dotbot-gh-extension \
        -p {{.PLUGINS_DIR}}/dotbot-include \
        -p {{.PLUGINS_DIR}}/dotbot-includes \
        --exit-on-failure \
        -d "$(pwd)" \
        -c "$(pwd)/install.yml"

  reinstall:
    label: "󰚩 Reinstall"
    desc: "Reinstall dotfiles using Dotbot"
    cmds:
    - task: dotbot:install
    - task: launchagents:install
    - task: install:macos:defaults
  install:
    label: "󰚩 Install"
    desc: "Install dotfiles using Dotbot"
    deps: [ generate ]
    cmds:
    - task: dotbot:install
    - task: launchagents:install
    - task: install:macos:defaults
  clean:
    label: "Clean"
    desc: "Clean generated files"
    cmds:
    - task: gitconfig:clean
    - platforms: [darwin]
      task: launchagents:clean
