---
version: '3'
#TODO(@s0cks): add functionality to run custom dotbot install. see scripts/install-dotbot.sh
tasks:
  install:dry-run:
    label: "󰚩 Install (dry-run)"
    desc: "Install dotfiles using Dotbot using dry-run mode."
    cmds:
    - >
      dotbot \
        -d "$(pwd)" \
        -c "$(pwd)/install.yml" \
        --dry-run
  install:verbose:
    label: "󰚩 Install"
    desc: "Install dotfiles using Dotbot using dry-run mode."
    cmds: 
    - >
      dotbot \
        -d "$(pwd)" \
        -c "$(pwd)/install.yml" \
        --verbose
  install:only:
    label: "󰚩 Install"
    desc: "Install dotfiles using Dotbot"
    cmds: 
    - >
      dotbot \
        -d "$(pwd)" \
        -c "$(pwd)/install.yml" \
        --only {{.CLI_ARGS}}
  install:except:
    label: "󰚩 Install"
    desc: "Install dotfiles using Dotbot"
    cmds: 
    - >
      dotbot \
        -d "$(pwd)" \
        -c "$(pwd)/install.yml" \
        --except {{.CLI_ARGS}}
  install:
    label: "󰚩 Install"
    desc: "Install dotfiles using Dotbot using dry-run mode."
    cmds: 
    - >
      dotbot \
        -d "$(pwd)" \
        -c "$(pwd)/install.yml" \
        {{.CLI_ARGS}}
  default:
    cmds:
    - task: install
