version: '3'
includes:
  jsonnet:
    internal: true
    taskfile: ../tasks/jsonnet.yml
  clean:
    interal: true
    taskfile: ../tasks/clean.yml
tasks:
  build:
    deps:
    - clean
    desc: "Generate ssh config using Jsonnet"
    cmds:
    - task: jsonnet:build
      vars:
        JSONNET_SOURCE: "ssh.jsonnet"
        JSONNET_INCLUDES: "-J .. -J . -J ../libs/ssh.libsonnet/"
        JSONNET_EXTRAS: "--ext-str GH_ID_RSA=id_rsa"
  clean:config:
    desc: "Clean ssh config"
    cmds:
    - task: clean:target
      vars:
        TARGETS: config
  clean:
    parallel: true
    cmds:
    - task: clean:config
  install:
    deps:
    - build
    cmds:
    - ./bin/install
  default:
    cmds:
    - task: build
