local Comment(lines) = 
  [
    "# %(line)s" % { line: line }, for line in (if std.isArray(lines) then lines else [ lines ])
  ];
local Styles(styles) = 
  {
    ["styles.%(name)s" % { name: section.key }]: section.value
    for section in std.objectKeysValues(styles) 
  };

{
  Bottom(styles):
    std.lines(Comment([
      "*** Do not edit ***",
      "This file is auto-generated by Jsonnet",
    ])) +
    std.manifestToml(
      Styles(styles)
    ),
}
