---
version: '3'
platforms: [darwin]
vars:
  USER_ID:
    sh: id -u
  DOMAIN: "gui/{{.USER_ID}}"
  COMPANY: "io.github.s0cks"
includes:
  launchctl:
    taskfile: ./launchctl.yml
    internal: true
    dir: "~/Library/LaunchAgents/"
  jsonnet:
    taskfile: ../../taskfiles/jsonnet.yml
    internal: true
tasks:
  generate:aria2:
    label: "Generate aria2.plist"
    desc: "Generate aria2 plist using Jsonnet"
    dir: "{{.TASKFILE_DIR}}"
    cmds:
    - task: jsonnet:generate
      vars:
        JSONNET_SOURCES: launch_agents.jsonnet
        JSONNET_EXTRAS: --ext-str COMPANY=io.github.s0cks --ext-str USER_HOME="~" --ext-str ARIA2_HOME --ext-str XDG_CONFIG_HOME --ext-str HOMEBREW_BIN="$HOMEBREW_REPOSITORY/bin" --ext-str ARIA2_SECRET --ext-str ARIA2_USER_AGENT
    sources:
    - launch_agents.jsonnet
    - templates/aria2.plist
    generates:
    - generated/io.github.s0cks.aria2.plist
  generate:kitty:
    label: "Generate kitty.plist"
    desc: "Generate kitty plist using Jsonnet"
    dir: "{{.TASKFILE_DIR}}"
    cmds:
    - task: jsonnet:generate
      vars:
        JSONNET_SOURCES: launch_agents.jsonnet
        JSONNET_EXTRAS: >
          --ext-str COMPANY=io.github.s0cks \
          --ext-str USER_HOME="~" \
          --ext-str ARIA2_HOME \
          --ext-str XDG_CONFIG_HOME \
          --ext-str HOMEBREW_BIN="$HOMEBREW_REPOSITORY/bin" \
          --ext-str ARIA2_SECRET \
          --ext-str ARIA2_USER_AGENT
    sources:
    - templates/kitty.plist
    - launch_agents.jsonnet
    generates:
    - generated/io.github.s0cks.kitty.plist
  generate:
    label: "Generate LaunchControl plist files"
    desc: "Generate LaunchControl plist files using Jsonnet"
    cmds:
    - task: generate:aria2
    - task: generate:kitty
  install:aria2:
    label: Install aria2 service
    cmds:
    - task: launchctl:bootstrap
      vars:
        SERVICE: "{{.COMPANY}}.aria2"
        DOMAIN:
          ref: .DOMAIN
  install:kitty:
    label: Install kitty service
    cmds:
    - task: launchctl:bootstrap
      vars:
        SERVICE: "{{.COMPANY}}.kitty"
        DOMAIN:
          ref: .DOMAIN
  install:
    label: "Install LaunchControl services"
    cmds:
    - task: install:aria2
    - task: install:kitty
  clean:
    cmds:
    - rm -rf *
