version: '3'
tasks:
  generate:
    internal: true
    cmds:
    - jsonnet {{.JSONNET_INCLUDES}} -S -m {{.JSONNET_BUILD_DIR}} {{.JSONNET_SOURCE}} {{.JSONNET_EXTRAS}}
    vars:
      JSONNET_INCLUDES: "-J .. -J ."
      JSONNET_BUILD_DIR: "."
      JSONNET_SOURCE: "generate.jsonnet"
      JSONNET_EXTRAS: "--ext-str OS=$(uname)"
    generates:
    - .zprofile
    - .zaliases
    - .zshenv
    - .zimrc
    - .zstyles
    - .zshrc
    - .zkeys
    - .hushlogin
  clean-generated:
    internal: true
    cmds:
    - >
      rm -rf \
        .zprofile \
        .zaliases \
        .zshenv \
        .zimrc \
        .zstyles \
        .zshrc \
        .zkeys \
        .hushlogin \
        hushlogin
  copy-generated:
    internal: true
    cmds:
    - >
      cp \
        .zprofile \
        .zaliases \
        .zshenv \
        .zimrc \
        .zstyles \
        .zshrc \
        .zkeys \
        .hushlogin \
        {{.TARGET_DIR}}
  build:
    cmds:
    - task: generate
      dir: .
  install:
    cmds:
    - task: generate
      dir: .
    - task: copy-generated
      dir: .
      vars:
        TARGET_DIR: ~/
  install:clean:
    cmds:
    - task: clean-generated
  clean:
    cmds:
    - task: clean-generated
      dir: .
  default:
    cmds:
    - task: build
