version: '3'
tasks:
  generate:
    desc: "Generate files using Jsonnet"
    cmds:
    - jsonnet {{.JSONNET_INCLUDES}} -S -m . {{.JSONNET_SOURCE}}
    vars:
      JSONNET_INCLUDES: "-J .. -J ."
      JSONNET_SOURCE: "generate.jsonnet"
    # sources:
    # - generate.jsonnet
    # - source_file_extensions.json
    # - lib/**/*.libsonnet
    # - lib/**/_*.sh
    generates:
    - .zprofile
    - .zaliases
    - .zshenv
    - .zimrc
    - .zstyles
    - .zshrc
    - .zkeys
    - .hushlogin
  clean:
    desc: "Clean the generated files"
    cmds:
    - >
      rm -rf \
        .zprofile \
        .zaliases \
        .zshenv \
        .zimrc \
        .zstyles \
        .zshrc \
        .zkeys \
        .hushlogin
  default:
    cmds:
    - task: generate
