#!/usr/bin/env zsh

# organize
alias organize-test="organize sim --tags=debug --skip-tags=slow --working-dir=$HOME"
alias afk="open /System/Library/CoreServices/ScreenSaverEngine.app"
alias home="cd ~"
alias chrome="open -a /Applications/Google\ Chrome.app"
alias drive="open -a /Applications/Google\ Drive.app"
alias sheets="open -a /Applications/Google\ Sheets.app"
alias task-dry="task --dry"
alias emoji='emoji_fzf'
alias tetris='tetrs_tui'
alias tail='btail'
alias neofetch="fastfetch"
alias port-scan="rustscan"

alias weather="https -b 'wttr.in?format=3'"

alias cpwd="pwd | cb"

# npm
alias npmug='npm uninstall --global'
alias npmig="npm i -g"
alias npmR='npm run'

# git
alias Gbw='git browse-web'

# neovim
alias vi=nvimz
alias vim=nvimz

# cat
alias cat='bat --paging=never --plain'

# bw
alias bwl="bw login --passwordenv BITWARDENCLI_PASS"

# yazi
alias yazi="yz"

# vtop
alias vtop="vtop --theme catppuccin-mocha-lavender"

# gpg
alias gpgep="gpg -r $GPG_ID --armor --export"
alias gpglk="gpg --list-keys --keyid-format LONG"
alias gpglsk="gpg --list-secret-keys --keyid-format LONG"
alias gpgepcb="gpgep | cb"

# eza
local eza_params=(
  '--git' '--icons' '--group' '--group-directories-first'
  '--time-style=long-iso' '--color-scale=all' '--color'
)
[[ ! -z $_EZA_PARAMS ]] && eza_params=($_EZA_PARAMS)

alias ls="eza --group-directories-first ${(j: :)_EZA_PARAMS} $@"
alias l="eza --git-ignore --group-directories-first ${(j: :)_EZA_PARAMS}"
alias ll="eza --all --header --long --group-directories-first ${EZA_PARAMS}"
alias llm="eza --all --header --long --sort=modified --group-directories-first ${_EZA_PARAMS}"
alias la='eza -lbhHigUmuSa'
alias lx='eza -lbhHigUmuSa@'
alias lt='eza --tree $eza_params'

# cargo
alias cargo-ls="cargo install --list"
alias Gl="serie"
alias tree="lstr -a -g -G --icons"
alias dic='echo 𓂺'

# global aliases
alias -g NE="2>/dev/null"
alias -g NO=">/dev/null"
alias -g NUL=">/dev/null 2>&1"
alias -g JQ="| jq"
alias -g GREP="| grep "
alias -g CP="| cb"

# suffix aliases
alias -s json="bat" #TODO(@s0cks): should change this to a better jq browser
alias -s txt="bat"
alias -s md="glow"
alias -s html="open"
local source_file_extensions=(
  # go
  "go"
  # rust
  "rs"
  # python
  "py"
  # javascript
  "js"
  # typescript
  "ts"
  # javaa
  "java"
  # scala
  "scala"
  # c
  "c"
  "h"
  # c++ units
  "cc"
  "cpp"
  "cxx"
  # c++ headers
  "hh"
  "hpp"
  "hxx"
  # yaml
  "yml"
  "yaml"
  # jsonnet
  "jsonnet"
  "libsonnet"
)
for item in "${source_file_extensions[@]}"; do
  alias -s $item="$EDITOR"
done

# hashes
hash -d dls="$HOME/Downloads/"
hash -d proj="$HOME/Projects/"
hash -d dots="/usr/local/share/dotfiles/"
hash -d config="$HOME/.config/"
