#!/usr/bin/env zsh
# Start configuration added by Zim install {{{
#
# This is not sourced during shell startup, and it's only used to configure the
# zimfw plugin manager.
#

#
# zimfw Modules
#
zmodule environment
zmodule git
zmodule input
zmodule termtitle
zmodule utility
zmodule archive
zmodule decayofmind/zsh-fast-alias-tips
zmodule fzf
zmodule git-info

# AutoPair
# https://github.com/hlissner/zsh-autopair
zmodule hlissner/zsh-autopair

# DotUp
# https://github.com/toku-sa-n/zsh-dot-up
zmodule toku-sa-n/zsh-dot-up

# OpenAI
# https://github.com/antonjs/zsh-gpt
zmodule antonjs/zsh-gpt

# fzf-tab completion
# https://github.com/Aloxaf/fzf-tab
zmodule Aloxaf/fzf-tab

zmodule olets/zsh-abbr

#Forgit
# https://github.com/wfxr/forgit
[ -f $HOMEBREW_PREFIX/share/forgit/forgit.plugin.zsh ] && source $HOMEBREW_PREFIX/share/forgit/forgit.plugin.zsh
if [[ -f "${FORGIT_INSTALL_DIR}" ]]; then
  export PATH="${FORGIT_INSTALL_DIR}/bin:${PATH}"
fi

# Load Custom Modules
# TODO(@s0cks): #8 add thefuck back
# zmodule $ZMODULES_DIR/zim-thefuck/
ZMODULES_DIR="$HOME/.zim/modules"
zmodule s0cks/zsh-autoenv
zmodule s0cks/zsh-starship --if '[[ \$+commands[starship] ]]'
zmodule s0cks/zsh-yeoman --if '[[ \$+commands[yo] ]]'
zmodule s0cks/zsh-zoxide --if '[[ \$+commands[zoxide] ]]'
zmodule s0cks/zsh-atuin --if '[[ \$+commands[atuin] ]]'
zmodule s0cks/zsh-mise --if '[[ \$+commands[mise] ]]'
zmodule s0cks/zsh-cargo --if '[[ \$+commands[rust] && \$+commands[cargo] ]]'
zmodule s0cks/zsh-zellij-sessionizer --if '[[ \$+commands[zellij] ]]'
zmodule $ZMODULES_DIR/zsh-tmux-sessionizer/ --if '[[ \$+commands[tmux] && \$+commands[fzf] ]]' -f 'functions/tmux-sessionizer' -a 'tmux-sessionizer'

#
# Completion
#

# Additional completion definitions for Zsh.
# Enables and configures smart and extensive tab completion.
# completion must be sourced after all modules that add completion definitions.
zmodule zsh-users/zsh-completions --fpath src
zmodule completion

#
# Modules that must be initialized last
#
zmodule zdharma-continuum/fast-syntax-highlighting
zmodule zsh-users/zsh-history-substring-search
zmodule zsh-users/zsh-autosuggestions
# }}} End configuration added by Zim install

zmodule olets/zsh-autosuggestions-abbreviations-strategy

# Bitwarden CLI
zmodule Game4Move78/zsh-bitwarden
# TODO: implement fzf + bitwarden integration:
# https://github.com/kalsowerus/zsh-bitwarden

# TODO:
# NPM Completion
# https://github.com/lukechilds/zsh-better-npm-completion
# zmodule lukechilds/zsh-better-npm-completion

zmodule s0cks/zsh-vcpkg --if '[[ \$+command[vcpkg] ]]'
