#!/usr/bin/env zsh
# ┌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
# ╎                           User                            ╎
# └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
export USEREMAIL='tazz@tazz.cloud'

# ┌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
# ╎                            GPG                            ╎
# └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
GPG_TTY=$(tty)
export GPG_TTY
export GPG_ID="tazz@tazz.cloud"
export GPG_KEY="A7E49DD5"

# ┌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
# ╎                          Secrets                          ╎
# └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
ZPROFILE_SECRETS_FILE="$HOME/.zprofile_secrets"
decrypt_secrets() {
  gpg --quiet --yes -d -o "${ZPROFILE_SECRETS_FILE}" "${ZPROFILE_SECRETS_FILE}.gpg"
}

decrypt_secrets
# shellcheck source=/dev/null
source "$ZPROFILE_SECRETS_FILE"
rm "${ZPROFILE_SECRETS_FILE}"
unset ZPROFILE_SECRETS_FILE
unset decrypt_secrets
