#!/usr/bin/env zsh
if [[ "$(arch)" == "arm64" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ "$(arch)" == "x86_64" || "$(arch)" == "i386" ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
else
  echo "invalid archiecture: $(arch)"
  return 1
fi
export PATH="$(brew --prefix)/bin:$PATH"

# ┌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
# ╎                      zimfw Pre-Init                       ╎
# └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
# autoloads
autoload -Uz colors && colors
autoload -Uz /usr/local/share/zsh/functions/*(:t)

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^E' edit-command-line

# apply llvm from homebrew
export PATH="$(brew --prefix llvm)/bin:$PATH"
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"

# apply zsh styles
source "$HOME/.zstyles"

export ZSH_AUTOSUGGEST_STRATEGY=(abbreviations $ZSH_AUTOSUGGEST_STRATEGY)

# ┌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
# ╎                        zimfw Init                         ╎
# └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim
# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  if (( ${+commands[curl]} )); then
    curl -fsSL --create-dirs -o "$ZIM_HOME/zimfw.zsh" "https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh"
  else
    mkdir -p ${ZIM_HOME} && wget -nv -O ${ZIM_HOME}/zimfw.zsh https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  fi
fi
# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZIM_CONFIG_FILE:-${ZDOTDIR:-${HOME}}/.zimrc} ]]; then
  source ${ZIM_HOME}/zimfw.zsh init
fi
# zim init
source ${ZIM_HOME}/init.zsh

# ┌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
# ╎                      zimfw Post-Init                      ╎
# └╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
zmodload -F zsh/terminfo +p:terminfo

source "$HOME/.zsh_custom/fz.sh" #TODO(@s0cks): wtf is this?
source "$HOME/.zkeys"
source "$HOME/.zaliases"
source <(pay-respects zsh)

#TODO(@s0cks): is this necessary?
if (( $+command[docker] )); then
  fpath=("$HOME/.docker/completions" $fpath)
fi

# set fast-zsh-highlighting theme to flexoki-dark/light based on MacOS theme
#TODO(@s0cks): figure out how to get this in zstyles?
if [[ $(uname) == "Darwin" ]]; then
  if macos-is-dark; then
    fast-theme -q XDG:flexoki-dark
  else
    fast-theme -q XDG:flexoki-light
  fi
fi

# luarocks
if [[ $+commands[luarocks] ]]; then
  source <(luarocks path)
fi

gpg-export-sk() {
  local KEY_ID="$1"
  local args=()
  if [[ "$#" > 1 ]]; then
    local OUTPUT_FILE="$2"
    args+=(
      "--output"
      "$OUTPUT_FILE"
    )
  fi
  args+=(
    "--armor"
    "--export-secret-key"
    "$KEY_ID"
  )
  gpg $args
}

fzfpath() {
  <<<${(F)fpath} | fzf
}

fzpath() {
  <<<${(F)path} | fzf
}

cat-fpath() {
  <<<${(F)fpath}
}

cat-path() {
  <<<${(F)path}
}

edit-path() {
  local path_file=$(mktemp -p /tmp path.XXXXX)
  echo "$(<<<${(F)path})" >> "$path_file"
  $EDITOR "$path_file"
  local lines=("${(f)$(<$path_file)}")
  export PATH="${(j[:])lines}"
}

# llvm
#TODO(@s0cks): is this necessary?
export PATH="$(brew --prefix llvm)/bin:$PATH"
export CC=clang
export CXX=clang++
export LD=ld.lld
export AR=llvm-ar
export RANLIB=llvm-ranlib

#TODO(@s0cks): remove this once these values are configured  properly using the theme
unset ZLS_COLORS
unset LS_COLORS
