---
version: '3'
includes:
  jsonnet:
    taskfile: ../../tasks/jsonnet.yml
    internal: true
tasks:
  build:
    label: "Generate git config"
    desc: "Generate git configuration using Jsonnet"
    deps:
    - clean
    cmds:
    - task: jsonnet:build
      vars:
        JSONNET_SOURCE: generate.jsonnet
        JSONNET_EXTRAS: --ext-str GPG_EXEC=$()
    sources:
    - generate.jsonnet
    generates:
    - config
    - s0cks.gitconfig
    - tazz.gitconfig
  clean:
    cmds:
    - rm -rfv config *.gitconfig
  install:
    cmds:
    - task: jsonnet:build
      vars:
        JSONNET_SOURCE: generate.jsonnet
        JSONNET_EXTRAS: --ext-str GPG_EXEC=$(which gpg)
        JSONNET_BUILD_DIR: "$XDG_CONFIG_HOME/git"
    sources:
    - generate.jsonnet
    generates:
    - config
    - s0cks.gitconfig
    - tazz.gitconfig
  default:
    cmds:
    - task: build
